version: '2'

volumes:
  huggingface:
  models:

services:
  dreamlike-trainer:
    container_name: dreamlike-trainer
    restart: always
    image: dreamlike-trainer
    volumes:
      - huggingface:/root/.cache/huggingface
      - models:/workspace/models-cache
      - ./models:/workspace/models
      - ./projects:/workspace/projects
      - ./datasets:/workspace/datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
