version: '2'

volumes:
  huggingface_cache:
  models_cache:

services:
  dreamlike-trainer:
    container_name: dreamlike-trainer
    restart: always
    image: dreamlike-trainer
    stdin_open: true
    tty: true
    volumes:
      - huggingface_cache:/root/.cache/huggingface
      - models_cache:/workspace/models_cache
      - ./models_cache.txt:/workspace/models_cache.txt
      - ./models:/workspace/models
      - ./projects:/workspace/projects
      - ./datasets:/workspace/datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
