version: '2'

volumes:
  huggingface_cache:
  models_cache:
  docker_datasets:

services:
  dreamlike-trainer:
    container_name: dreamlike-trainer
    restart: always
    image: dreamlike-trainer
    stdin_open: true
    tty: true
    volumes:
      - huggingface_cache:/root/.cache/huggingface
      - models_cache:/workspace/models_cache
      - ./models_cache.txt:/workspace/models_cache.txt
      - ./models:/workspace/models
      - ./configs:/workspace/configs
      - ./runs:/workspace/runs
      - ./datasets:/workspace/datasets
      - docker_datasets:/workspace/docker_datasets
      - "D:\\:/workspace/van_gogh"
      - "E:\\:/workspace/disco"
    ports:
      - "6006:6006"
    cap_add:
      - SYS_PTRACE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
