version: '2'

volumes:
  huggingface_cache:
  models_cache:
  docker_datasets:

services:
  dreamlike-trainer:
    container_name: dreamlike-trainer
    restart: always
    image: index.docker.io/dreamlikeart/dreamlike-trainer:latest
    stdin_open: true
    tty: true
    volumes:
      - huggingface_cache:/root/.cache/huggingface
      - models_cache:/workspace/models_cache
      - ./models_cache.txt:/workspace/models_cache.txt
      - ./models:/workspace/models
      - ./configs:/workspace/configs
      - ./runs:/workspace/runs
      - ./datasets:/workspace/datasets
      - docker_datasets:/workspace/docker_datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
